### ISSUE TITLE
Config require bug

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-entity-generator#117]
**Steps to reproduce**

- Install version 3.2.2
- make any action with the app (e.g. open guest route)

**Expected results**

Not errors

**Actual result**

<img width="1389" alt="image" src="https://github.com/user-attachments/assets/ce285810-d9ea-4ffc-8cad-34a5e075a773">

**Comment by pirs1337** [comment]
fixed

**Comment by DenTray** [comment]
@pirs1337 thanks! works fine, released in 3.2.3
