### ISSUE TITLE
Change resources generation logic

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-entity-generator#125]
At the moment http resource generating with the default `data` wrapper, so initially generated "creation" tests are not working.

Need to make next changes to the resource template and resource path:
1. Resource should be generated inside the entity name subdirectory (e.g. `Post` resource should be places inside the next dir `app/Http/Reources/Post`)
2. Each resource should have public static $wrap property with the `null` value (later it will be moved to some `BaseResource` class)

**Comment by yogyrton** [comment]
@DenTray Done. Please check it

**Comment by DenTray** [comment]
@yogyrton looks great! thanks! Releases in 3.3
