### ISSUE TITLE
Generate Nova resource

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-entity-generator#19]
At first please check that the native `php artisan nova:resource Post` console command not support generation resource fields by the DB fields.

The class should be generated if no flags passed to the command. It shouldn't generated with `--only-api` and `--only-entity` flags.

We also need in `--only-nova-resource` flag.

**Comment by pirs1337** [comment]
@DenTray, ready for testing

**Comment by DenTray** [comment]
@NikitaYakovlev could you please test it?

**Comment by NikitaYakovlev** [comment]
- if generate all and Nova is not installed - need to add notification that Nova is not installed and NovaResource is skipped.
- similarly when generating only NovaResource with the `--only-nova-resource` option


- If the field is required, it should also be made required in the generated NovaResource.
`->rules('required')`

**Comment by DenTray** [comment]
@Adil9994 I also can recreate NovaResource if it already exists, but for other classes - it will throw an exception

**Comment by Adil9994** [comment]
@DenTray done

**Comment by DenTray** [comment]
@Adil9994 works good for passed fields, but the main idea was to get actual DB fields cause the resource may be generated later. I'll create the separate issue for it.
