### ISSUE TITLE
Generate factory as a separate class for the Laravel 8+

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-entity-generator#20]
For the Laravel versions less than 8 - it should works as earlier.

**Comment by pirs1337** [comment]
@DenTray, ready for testing

**Comment by DenTray** [comment]
1. We need to make some refactoring of the stubs configs naming:
- `factory` -> `legacy_factory`
- `factory_separate_class` -> `factory`
- `empty_factory` -> `legacy_empty_factory`
- `seeder` -> `legacy_seeder`
- `seeder_for_separate_factory` -> `seeder`

2. Bug with the DatabaseSeeder class

<img width="492" alt="image" src="https://user-images.githubusercontent.com/9486872/222040901-4cfbd5ed-4711-4ab0-b46c-3ddaf3c5de45.png">

- missing namespace
- missing new generated seeder inside the `use` block

3. Bug with generating entity on Laravel >= 8

<img width="986" alt="image" src="https://user-images.githubusercontent.com/9486872/222043740-6950a481-75eb-4791-ab6b-9a0fcc84b5a5.png">

command trying to access to `database/seeds/DatabaseSeeder.php` instead of `database/seeders/DatabaseSeeder.php`

4. Bug with generating entity on Laravel 5.8

<img width="951" alt="image" src="https://user-images.githubusercontent.com/9486872/222056106-b648be37-b79c-4f13-bb1a-1a6d241c3428.png">

**Comment by DenTray** [comment]
@NikitaYakovlev I've found another one bug and can not check previous fixes, could you please take a look?

version: dev-master
log:

```sh
> php artisan make:entity Car

Created a new Model: Car
Created a new Repository: CarRepository
Created a new Service: CarService
Created a new Request: GetCarRequest
Created a new Request: SearchCarsRequest
Created a new Request: DeleteCarRequest
Created a new Request: CreateCarRequest
Created a new Request: UpdateCarRequest
Created a new Resource: CarResource
Created a new Route: Route::post('cars', [CarController::class, 'create']);
Created a new Route: Route::put('cars/{id}', [CarController::class, 'update']);
Created a new Route: Route::delete('cars/{id}', [CarController::class, 'delete']);
Created a new Route: Route::get('cars/{id}', [CarController::class, 'get']);
Created a new Route: Route::get('cars', [CarController::class, 'search']);
Created a new Controller: CarController
Created a new Migration: cars_create_table
Created a new Factory: CarFactory

   InvalidArgumentException 

  Unable to locate factory for [App\Models\Media].

  at vendor/laravel/legacy-factories/src/FactoryBuilder.php:273
    269▕      */
    270▕     protected function getRawAttributes(array $attributes = [])
    271▕     {
    272▕         if (! isset($this->definitions[$this->class])) {
  ➜ 273▕             throw new InvalidArgumentException("Unable to locate factory for [{$this->class}].");
    274▕         }
    275▕ 
    276▕         $definition = call_user_func(
    277▕             $this->definitions[$this->class],

      +8 vendor frames 
  9   [internal]:0
      RonasIT\Support\Generators\TestsGenerator::RonasIT\Support\Generators\{closure}("Media")

      +19 vendor frames 
  29  artisan:23
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

```

I really hasn't the Media model, but not sure that it should fail generating empty entity

**Comment by DenTray** [comment]
Works fine
