### ISSUE TITLE
Remove required rule for search request with required boolean field

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-entity-generator#33]
After generating entity with `-B` option (generate boolean required field) if use the required validation rule for this field in the search request

<img width="476" alt="image" src="https://github.com/RonasIT/laravel-entity-generator/assets/9486872/829f9a6d-e4d9-4bfb-8b94-d04442050830">

in fact it disallows to pass `false` value here

Also we need to remore required validation rule on create request for the boolean fields aswell. It should add `present` valdiation rule

**Comment by yogyrton** [comment]
@DenTray Done. Check it please

**Comment by KonstantinLapkovsky** [comment]
@DenTray done! Please check it

**Comment by DenTray** [comment]
@KonstantinLapkovsky great, thanks! works as expected now!
