### ISSUE TITLE
Update migration template

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-entity-generator#43]
Since Laravel 9 native generator creates a migration via anonymus class

<img width="654" alt="image" src="https://github.com/RonasIT/laravel-entity-generator/assets/9486872/2396eff5-4dfa-4e55-bfea-ad9617f01390">

Legacy style:
<img width="647" alt="image" src="https://github.com/RonasIT/laravel-entity-generator/assets/9486872/d84e3ee4-e9db-4fff-a556-eb4aba7e7584">

We need to update templates logic to use new style for projects with Laravel >= 9

**Comment by yogyrton** [comment]
@DenTray Done. Check it please

**Comment by DenTray** [comment]
@yogyrton not works for me. I've generated new entity in Laravel 5.8 and it's generates anonym class

<img width="638" alt="image" src="https://github.com/RonasIT/laravel-entity-generator/assets/9486872/790ee603-9065-4619-b7b9-5336bc3f1b09">

**Comment by DenTray** [comment]
@yogyrton works as expected, thanks!
