### ISSUE TITLE
Use reflection to detect model relations

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-entity-generator#50]
At the moment `getRelatedModels` method works based on regexp of file content https://github.com/RonasIT/laravel-entity-generator/blob/master/src/Generators/TestsGenerator.php#L267

We need to use reflection instead

**Comment by pirs1337** [comment]
done

**Comment by DenTray** [comment]
@pirs1337 seems work fine, thanks!

Released in 3.2.3
