### ISSUE TITLE
Circular relations bug on generating tests

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-entity-generator#51]
How to reproduce:
Try to generate an entity with `--only-tests` option. Entity should have non directly circular relations.

E.g. Generate tests by entity `Address`. When `Address` has `User` relation and `User` has `Addresses` relation

**Comment by pirs1337** [comment]
@DenTray can we check this again, I couldn't

**Comment by DenTray** [comment]
@pirs1337 seems fixed with another tasks, closed as resolved in 3.2.3
