### ISSUE TITLE
Unable to generate test

### ISSUE THREAD

**Issue by Goodmain** [RonasIT/laravel-entity-generator#55]
I'm using the fresh version of empty project. When I tried to generate a new entity I got an error:

<img width="1262" alt="image" src="https://github.com/RonasIT/laravel-entity-generator/assets/1735581/6628fb2d-925b-4ed1-9b16-2d02eb5ed70f">

As I see the empty project stores translations at the `lang/en/` folder while entity generator attempt to write into `resources/lang/en/` folder instead. We should sync pathes of the translation folders.

**Comment by KonstantinLapkovsky** [comment]
@Goodmain @DenTray this bug is already resolved on the master branch

**Comment by DenTray** [comment]
Works fine
