### ISSUE TITLE
Not PSR naming when entity name started from the lower case

### ISSUE THREAD

**Issue by Goodmain** [RonasIT/laravel-entity-generator#56]
When I generated a new entity I occasionaly entered name in a lower case. As the result I got the following naming which breaks the PSR

<img width="844" alt="image" src="https://github.com/RonasIT/laravel-entity-generator/assets/1735581/48e06b13-91e3-4096-b901-280daa824c56">

Maybe we should convert the entered value to the CamelCase?

**Comment by DenTray** [comment]
@Goodmain thanks for your question. I believe it is a bug, so I'll mark it and plan to the next version
