### ISSUE TITLE
Use model test states in tests generator

### ISSUE THREAD

**Issue by DenTray** [RonasIT/laravel-entity-generator#97]
Need to add using ModelTestState in test classes generation. ModelTestStates should be used in all places instead of `assertDatabaseHas` and `assertDatabaseMissing` helpers

Reference: https://github.com/RonasIT/laravel-helpers/blob/master/src/Tests/ModelTestState.php

**Comment by DenTray** [comment]
@pirs1337 seems test template is broken now, `actingAs` method is not using anymore, please check what happens. Could you also please assert that no changes for test `testUpdateNotExists`?

**Comment by pirs1337** [comment]
> @pirs1337 seems test template is broken now, `actingAs` method is not using anymore, please check what happens. Could you also please assert that no changes for test `testUpdateNotExists`?

There is a condition: you need to have a `UserFactory` for the `ActingAs` method to be used in the generated test class. - https://github.com/RonasIT/laravel-entity-generator/blob/master/src/Generators/AbstractTestsGenerator.php#L241, should i remove it?

**Comment by DenTray** [comment]
@pirs1337 I've checked logic and yes, seems factory is not required https://github.com/RonasIT/laravel-entity-generator/blob/cbb2fe372e8fcb9a8e507b0ad8e6a567885514c4/src/Generators/AbstractTestsGenerator.php#L171

Please remove check for factory exists

**Comment by yogyrton** [comment]
@DenTray Done. Please check it

**Comment by DenTray** [comment]
released in https://github.com/RonasIT/laravel-entity-generator/releases/tag/3.2.4
